services:

  db:
    image: postgres:15-alpine
    restart: always

    container_name: taskdb

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: abhinav-23bcs181-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/taskdb?schema=public
    image: abhinav-23bcs181-task-backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: abhinav-23bcs181-task-frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    image: abhinav-23bcs181-task-frontend
    depends_on:
      - backend

volumes:
  postgres_data:

